# ==============================================================================
# cromwell-wes-service-e2e-test client (Secret + WalletClient + WalletPolicy)
# ==============================================================================
{{- $e2eSecretObj := (lookup "v1" "Secret" .Release.Namespace "cromwell-wes-service-e2e-test-client-credentials") | default dict }}
{{- if or (empty $e2eSecretObj)
          (and
            (hasKey $e2eSecretObj.metadata "annotations")
            (hasKey $e2eSecretObj.metadata.annotations "meta.helm.sh/release-name")
            (eq (get $e2eSecretObj.metadata.annotations "meta.helm.sh/release-name") .Release.Name))
}}
apiVersion: v1
kind: Secret
metadata:
  name: cromwell-wes-service-e2e-test-client-credentials
  labels:
    app: cromwell-wes-service
    type: test_wallet-client-credential
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $e2eSecretData := (get $e2eSecretObj "data") | default dict }}
  {{- $e2eClientSecret := (get $e2eSecretData "clientSecret") | default (randBytes 32 | b64dec | printf "%x" | b64enc) }}
  clientId: {{ b64enc "cromwell-wes-service-e2e-test" | quote }}
  clientSecret: {{ $e2eClientSecret | quote }}
{{- end }}

---

apiVersion: dnastack.com/v1
kind: WalletClient
metadata:
  name: cromwell-wes-service-e2e-test
  labels:
    app: cromwell-wes-service
spec:
  syncMode: CREATE_AND_UPDATE
  clientSecrets:
    - credentialId: default
      syncMode: CREATE_ONLY
      secretKeyRef:
        name: cromwell-wes-service-e2e-test-client-credentials
        key: clientSecret
    - credentialId: rotation-backup
      syncMode: CREATE_ONLY
      secretKeyRef:
        name: cromwell-wes-service-e2e-test-client-credentials
        key: clientSecret
  data:
    id: cromwell-wes-service-e2e-test
    name: "Client for end-to-end testing of cromwell-wes-service"
    grants:
      - audience: '{{- include "dnastack.workspacesWes.externalUrl" . }}'
        grantTypes:
          - client_credentials
        responseTypes:
          - token
        scopes:
          - name: wes
