app:
  service-info:
    auth-instruction-url: http://keycloak:8080.com
    supported-wes-versions:
    - "1.0.0"

    supported-file-system-protocols:
    - "gs"
    - "http"
    - "file"
    - "drs"
    workflow-engine-versions:
      cromwell: 42
    workflow-type-versions:
      WDL:
      - "draft-2"
      - "1.0"
  drs:
    supported-types:
    - "file"

server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: wes-service
    password: ""
    url: jdbc:postgresql://localhost/wes-service
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Fix for cosmetic error on startup `HHH000424: Disabling contextual LOB creation as createClob() method threw error`
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect