server:
  port: 8090
  error:
    include-message: always         # To include "message" attribute
    include-binding-errors: always  # To include "errors" attribute

spring:
  application:
    name: cromwell-wes-service
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/wes-service
    username: wes-service
    password: ""
    hikari:
      maximum-pool-size: 5
  zipkin:
    enabled: false # By default, it is DISABLED for the local development.
    base-url: http://localhost:9411
    sender:
      type: web
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Fix for cosmetic error on startup `HHH000424: Disabling contextual LOB creation as createClob() method threw error`
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  servlet:
    multipart:
      enabled: true

logging:
  level:
    org.springframework.security: INFO # set to DEBUG to find out why tokens are rejected

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,prometheus,loggers
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true

# App information
info:
  app:
    name: "wes-service"
    description: "Interface Layering WES API ontop of an execution engine"
    url: http://localhost:${server.port}
    version: "${project.version}"

build.version: @project.version@

app:
  url: ${wes.url}

wes:
  url: ${info.app.url}
  service-info:
    auth-instruction-url: "${wes.auth.token-issuers[0].issuer-uri}/.well-known/openid-configuration"
    supported-wes-versions:
      - "1.0.0"
    supported-file-system-protocols:
      - "file"
      - "drs"
    workflow-engine-versions:
      cromwell: 47
    workflow-type-versions:
      WDL:
        - "draft-2"
        - "1.0"
    tags:
      object-access-token-attachment-name: "tokens.json"
      cromwell-options-attachment-name: "options.json"
      dependencies-zip-attachment-name: "dependencies.zip"
  drs:
    supported-access-types:
      - file
  blob-storage-client:
    name: LOCAL
    gcp:
      project:
      stagingLocation:
    abs:
      container:
      connection-string:
      staging-path:
    local:
      staging-path: /home/patrick/tools/cromwell/v54/uploads

  auth:
    # Defaults included in wallet dev setup
    service-account-authentication-uri: http://localhost:8081/oauth/token
    service-account-client-id: wes-service
    service-account-secret: wes-service
    token-issuers:
      # Default Token issuer to use
      - issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth/jwks
        audiences:
          - http://localhost:8090
          - http://wes-service.local
          - http://wes.local
          - wes.local
    validator:
      policy-evaluation-requester: ${info.app.url}
      policy-evaluation-uri: ${wes.auth.token-issuers[0].issuer-uri}/policies/evaluations
  enable-multi-tenant-support: false
  cromwell:
    defaultWorkflowOptions:
      write_to_cache: false
      read_from_cache: false
  registry:
    client-id: wes-service
    client-secret: dev-secret-never-use-in-prod
    grant-type: "urn:ietf:params:oauth:grant-type:device_code"
    token-uri: ${wes.auth.token-issuers[0].issuer-uri}/oauth/token
    device-code-uri: ${wes.auth.token-issuers[0].issuer-uri}/oauth/device/code
    services:
      wes:
        id: wes
        name: DNAstack Workbench - WES Service
        type:
          group: org.ga4gh
          artifact: wes
          version: v1.1
        description: Compliant with the <a href='https://github.com/ga4gh/workflow-execution-service-schemas' target='_blank'>WES</a> standard by the <a href='https://www.ga4gh.org/' target='_blank'>Global Alliance for Genomics and Health</a>."
        organization:
          name: DNAstack
          url: https://dnastack.com
        version: ${build.version}
        url: ${wes.url}/ga4gh/wes/v1/
        authentication:
          - accessTokenUrl: ${wes.registry.token-uri}
            clientId: ${wes.registry.client-id}
            clientSecret: ${wes.registry.client-secret}
            deviceCodeUrl: ${wes.registry.device-code-uri}
            grantType: ${wes.registry.grant-type}
            resource: ${wes.url}/ga4gh/wes/v1/
            type: oauth2
# Auditing
auditing:
  enabled: true
  batch-processing-enabled: true
  scheduling:
    batch-emit:
      cron: 0/10 * * ? * *
  service-client-id: ewes-service
  publisher:
    events-uri: ${auditing.oauth-client.audience}/events
    events-batch-uri: ${auditing.oauth-client.audience}/events/batch
    give-up-after: 5
    delay-between-tries-in-millis: 250
  oauth-client:
    client-id: wes-service
    client-secret: dev-secret-never-use-in-prod
    scopes: audit:create
    audience: http://localhost:8888
    resource: ${auditing.publisher.events-uri}
    actions: [ "audit:create" ]
    token-uri: ${wes.auth.token-issuers[0].issuer-uri}/oauth/token
    token-issuers-uris: ${wes.auth.token-issuers[0].issuer-uri}
    policy-evaluation-requester: ${wes.auth.validator.policy-evaluation-requester}
    policy-evaluation-uri: ${wes.auth.validator.policy-evaluation-uri}
  json-printer-style: dense_print


springdoc:
  oAuthFlow:
    authorizationUrl: http://localhost:8081/oauth/authorize
    tokenUrl: http://localhost:8081/oauth/token
  api-docs:
    path: /docs/openapi.json
  swagger-ui:
    path: /docs/swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: "local-dev"

logging:
  level:
    com.dnastack: DEBUG

---
spring:
  config:
    activate:
      on-profile: "publish-external"
auditing:
  publish-external: true