wes:
  service-info:
    auth-instruction-url: "https://wallet.staging.dnastack.com/.well-known/openid-configuration"
    supported-wes-versions:
      - "1.0.0"
    supported-file-system-protocols:
      - "file"
      - "drs"
    workflow-engine-versions:
      cromwell: 47
    workflow-type-versions:
      WDL:
        - "draft-2"
        - "1.0"
    tags:
      object-access-token-attachment-name: "tokens.json"
      cromwell-options-attachment-name: "options.json"
      dependencies-zip-attachment-name: "dependencies.zip"
  drs:
    supported-access-types:
      - file
  transfer:
    enabled: false
    object-transfer-uri: http://localhost:8086
    # Needs to be set
    staging-directory:
  auth:
    # Defaults included in wallet dev setup
    service-account-authentication-uri: http://localhost:8081/oauth/token
    service-account-client-id: wes-service
    service-account-secret: wes-service
    dev-token-issuer:
      rsa-public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxySDfhuXD+0khrgMX4Zq
        K4JBrexDoEK7gooBI6E1oYlX8nrQm6Z7G6QJtyFOTt04z9HR0fwGUDgaU9abBWzf
        /wJdABPTIUwlwB9yFAelF6jY9k2nVe/Agpbdlx4ylu2MbQ3ybCW8ma33UmQSK9/N
        R1R1aw3bKj5gvKF9/aWNLeObeipqXKZ/T3nD5/2O1BD8xzNZ+eQ6qWJKtWvVsq42
        B5Z9DNuvgmYYmPAc2OUQc9qhdsO1Jw8J58ZxBIFNC0h1/yaaeUuUtKMaw1VMOZqT
        7EjteeEujFVG4zqUPXaJNiFLd7kFkL65JEbxlCxFfh0b6SjJESNcwDHbSZt6EitG
        5QIDAQAB
        -----END PUBLIC KEY-----
      audiences:
        - wes-e2e-test
      issuer-uri: "https://testing.dnastack.com"
    token-issuers:
      # Default Token issuer to use
      - issuer-uri: https://wallet.staging.dnastack.com
        jwk-set-uri: https://wallet.staging.dnastack.com/oauth/jwks
      - issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth/jwks
        audiences:
          - http://localhost:8090
  enable-multi-tenant-support: false
  path-translations:
    - prefix: "http://localhost"
      replacement: "/home/patrick"
    - prefix: "/home/patrick/tools/cromwell/v42/"
      replacement: "some-path/"
    - prefix: "/home/patrick"
      replacement: "some-path/"
# App information
info:
  app:
    name: "wes-service"
    description: "Interface Layering WES API ontop of an execution engine"
    version: "${project.version}"

server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: wes-service
    password: ""
    url: jdbc:postgresql://localhost/wes-service
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Fix for cosmetic error on startup `HHH000424: Disabling contextual LOB creation as createClob() method threw error`
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
