wes:
  service-info:
    auth-instruction-url: "https://wep-keycloak.staging.dnastack.com/auth/realms/DNAstack/.well-known/openid-configuration"
    supported-wes-versions:
    - "1.0.0"

    supported-file-system-protocols:
    - "gs"
    - "http"
    - "file"
    - "drs"
    workflow-engine-versions:
      cromwell: 42
    workflow-type-versions:
      WDL:
      - "draft-2"
      - "1.0"
  drs:
    supported-types:
    - "file"
  transfer:
    enabled: false
    staging-directory: "gs://ds-test-uploading"
    object-transfer-uri: "https://object-transfer.staging.dnastack.com"
    external-account-uri: "https://external-accounts.staging.dnastack.com"
  auth:
    service-account-authentication-uri: "https://wep-keycloak.staging.dnastack.com/auth/realms/DNAstack/protocol/openid-connect/token"
    service-account-client-id: "wes-service"
    service-account-secret: "e5c145eb-2f2e-4d3e-949c-c5a9f247fd01"
    dev-token-issuer:
      rsa-public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxySDfhuXD+0khrgMX4Zq
        K4JBrexDoEK7gooBI6E1oYlX8nrQm6Z7G6QJtyFOTt04z9HR0fwGUDgaU9abBWzf
        /wJdABPTIUwlwB9yFAelF6jY9k2nVe/Agpbdlx4ylu2MbQ3ybCW8ma33UmQSK9/N
        R1R1aw3bKj5gvKF9/aWNLeObeipqXKZ/T3nD5/2O1BD8xzNZ+eQ6qWJKtWvVsq42
        B5Z9DNuvgmYYmPAc2OUQc9qhdsO1Jw8J58ZxBIFNC0h1/yaaeUuUtKMaw1VMOZqT
        7EjteeEujFVG4zqUPXaJNiFLd7kFkL65JEbxlCxFfh0b6SjJESNcwDHbSZt6EitG
        5QIDAQAB
        -----END PUBLIC KEY-----
      audiences:
      - wes-e2e-test
      issuer-uri: "https://testing.dnastack.com"
    token-issuers:
    - issuer-uri: "https://wep-keycloak.staging.dnastack.com/auth/realms/DNAstack"
      jwk-set-uri: "https://wep-keycloak.staging.dnastack.com/auth/realms/DNAstack/protocol/openid-connect/certs"
      audiences:
      - dnastack-client
    - issuer-uri: "https://data-access-manager.staging.dnastack.com"
      rsa-public-key: |
        -----BEGIN RSA PUBLIC KEY-----
        MIIBCgKCAQEAz0WC1eM5IFvnQuaQKt1z90QINJ+5PaH0TflUXMqeM/9bAsDaIbYZ
        zMu0uDNzSTVOOl5o1/mclo88wzS1E572VzOOsu6eXHzztpokHI5bbxbhDIrA+2o3
        wOsddFo+QvrMmR+I73ZqmVIuUd03Dhlk/i32Dk7NLOOSsn/WCEZUQ9vM7SuaWwZr
        NXBJ633MtgxOE/UEDnJ7gqZrllzBfDDKhgkG7nbRpoU9bSY3G6DwcjnmW2g3HVom
        6hZao6JWpcddP/7dvTY5sKYVjbSVIG4eJUqIZI2wSAxp/Fj9SPGl3nRqNkWJdkQl
        iMZxVlN2CZ481xaOK8jVjiN88LIZbMcPqwIDAQAB
        -----END RSA PUBLIC KEY-----
      audiences:
      - ddap-wes
  wdl:
    validator:
      url: "https://wdl-validator.staging.dnastack.com"
  enable-multi-tenant-support: false

# App information
info:
  app:
    name: "wes-service"
    description: "Interface Layering WES API ontop of an execution engine"
    version: "${project.version}"

server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: wes-service
    password: ""
    url: jdbc:postgresql://localhost/wes-service
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Fix for cosmetic error on startup `HHH000424: Disabling contextual LOB creation as createClob() method threw error`
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect