#!/usr/bin/env bash

set -e
set -x

# This script runs the maven build, including unit tests, assembles a fat jar with
# embedded web server, and packages the resulting thing in a Docker image that runs
# the server on startup. The image is tagged with the string passed in as the first argument.

# This script is invoked during CI build with the following arguments:
target_image_name=$1
app_name=$2
app_version=$3

# This script does all its staging in a directory called target for easy cleanup and effective .gitignore.
docker_context_dir=ci/impl/target
rm -rf ${docker_context_dir}
mkdir -p ${docker_context_dir}
# Allows us to pass settings.xml configured on local machine or CI server to access private Nexus repo
mkdir -p ${docker_context_dir}/.m2
cp -rp src .mvn mvnw pom.xml ${docker_context_dir}
cp ~/.m2/*.xml ${docker_context_dir}/.m2

docker build \
  --build-arg APP_NAME=${app_name} \
  --build-arg APP_VERSION=${app_version} \
  -t ${target_image_name} \
  ci/impl
