apiVersion: v2
name: workspaces-wes
description: Helm chart for the DNAstack Cromwell WES Service
type: application
version: 0.1.0

dependencies:
  - name: workbench-helm-library
    version: 0.5.0-1-gc75d596
    repository: oci://us-central1-docker.pkg.dev/dnastack-container-store/helm-charts
