name: Build, Test & Analyse

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-java-app:
    name: Build & Test Java App
    uses: ./.github/workflows/build-test-java-app.yml
    with:
      java-version: 21
    secrets:
      pat-with-read-packages-permission: ${{ secrets.AUTH_TOKEN }}
  code-analysis-and-dependency-check:
    name: Code Analysis and OWASP Dependency Check
    uses: ./.github/workflows/code-analysis-and-dependency-check.yml
    with:
      with-frontend: false
      java-version: 21
      code-coverage-enabled: true
    secrets:
      pat-with-read-packages-permission: ${{ secrets.AUTH_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}