name: Concourse Build Check

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@7c3b1aef57cde6747b17061e0e0861968e6b05b7
    with:
      pipeline_name: 'workbench-alpha'
      job_name: 'workspaces-wes-deploy-helm'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
