name: Concourse Build Check

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@dd17b167bbc317d901c33b414eb59d457c71c08d
    with:
      pipeline_name: 'workbench-alpha'
      job_name: 'workspaces-wes-deploy-helm'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
