name: Concourse Build Check

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@87fe32c51a9d3f4ebc8596f98ff4eecf0d974b5f
    with:
      pipeline_name: 'workbench-alpha'
      job_name: 'workspaces-wes-deploy-helm'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
